## Configuração do servidor
#server:
#  port: 8081
#  servlet:
#
#  application:
#    name: Sistema FATEXTIL
#  error:
#    include-message: always
#    include-stacktrace: always
#
#
#  # Configuração do Swagger
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

server:
  port: 8081
  address: localhost
  servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
      context-path: /api
  application:
      name: Sistema FATEXTIL
  error:
      include-message: always
      include-stacktrace: always
spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update # create-drop pode dar erro de alter table para constraints
        properties:
            hibernate:
                formatsql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
