# CONFIGURAÇÃO DO SERVIDOR
server:
  port: 8080
  servlet:
    context-path: /api
  application:
    name: Sistema FATEXTIL
  error:
    include-message: always
    include-stacktrace: always

# CONFIGURAÇÕES DE CONEXÃO COM O BANCO DE DADOS
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/academicodb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # HIBERNATE DDL AUTO (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update

    # CONFIGURAÇÃO QUE DEFINE A FORMA COMO O MAPEAMENTO DO JPA IRÁ TRABALHAR
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

      # LOGANDO/PRINT DOS COMANDOS SQL GERADOS PELO SPRING DATA
      show_sql: true
      format_sql: true

  # CONFIGURAÇÃO DO SWAGGER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
