-- Inserção de perfis de acesso padões
INSERT INTO PERFIL_ACESSO (NOME_PERFIL_ACESSO)
VALUES ('ROLE_ADMIN');
INSERT INTO PERFIL_ACESSO (NOME_PERFIL_ACESSO)
VALUES ('ROLE_VENDEDOR');
INSERT INTO PERFIL_ACESSO (NOME_PERFIL_ACESSO)
VALUES ('ROLE_DESIGNER');


-- Inserção de usuario padrão
INSERT INTO USUARIO (PERFIL_ACESSO_ID, FUNCIONARIO_ID, LOGIN, SENHA, ATIVO)
VALUES (2, 1, 'judah', '$2a$12$yi4tvcbIS5RsNkt8qQ07luEw3eGjmiVu6s8CyEteVzgFBSWRYUjeK', 1);